# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: AccessibilityChecker@1
  inputs:
    url: 'https://www.benday.com/2021/08/18/azure-devops-tip-handling-strings-in-yaml-pipelines/'
    tagoptions: 'wcag2a'
    testtitle: 'benday ado yaml string'

- task: AccessibilityChecker@1
  inputs:
    url: 'https://www.benday.com/'
    tagoptions: 'wcag2a'
    testtitle: 'benday homepage'
    